### ISSUE TITLE
Client crashing when rightclicking a chargepad (creative mode)

### ISSUE THREAD

**Issue by Sp0nge** [Myrathi/ChargePadsEx#2]
2013-05-06 22:01:25 [INFO] [STDERR] net.minecraft.util.ReportedException: Exception in world tick
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1877)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:834)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:759)
2013-05-06 22:01:25 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-05-06 22:01:25 [INFO] [STDERR] Caused by: java.lang.NoSuchFieldError: k
2013-05-06 22:01:25 [INFO] [STDERR]     at myrathi.ic2.chargepads.j.<init>(SourceFile:25)
2013-05-06 22:01:25 [INFO] [STDERR]     at myrathi.ic2.chargepads.proxy.ClientProxy.getClientGuiElement(SourceFile:29)
2013-05-06 22:01:25 [INFO] [STDERR]     at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:328)
2013-05-06 22:01:25 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:351)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2396)
2013-05-06 22:01:25 [INFO] [STDERR]     at cpw.mods.fml.common.network.OpenGuiPacket.execute(OpenGuiPacket.java:67)
2013-05-06 22:01:25 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.handleFMLPacket(FMLNetworkHandler.java:114)
2013-05-06 22:01:25 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:79)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1571)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:59)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:266)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:94)
2013-05-06 22:01:25 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1861)
2013-05-06 22:01:25 [INFO] [STDERR]     ... 3 more
2013-05-06 22:01:35 [INFO] [Minecraft-Client] Stopping!

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1919171264 bytes (1830 MB) / 2556493824 bytes (2438 MB) up to 9343074304 bytes (8910 MB)
    JVM Flags: 4 total; -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=128m -Xms512m -Xmx10024m
    AABB Pool Size: 16931 (948136 bytes; 0 MB) allocated, 1464 (81984 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.51 FML v5.2.5.686 Minecraft Forge 7.8.0.686 22 mods loaded, 22 mods active
    mcp{7.44} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.2.5.686} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.8.0.686} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    jammyfurniture{4.2} [Jammy Furniture Mod](1.5.1_Jammy_Furniture_Mod_V4.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LOTR{Beta v5.1 for Minecraft 1.5.2} [The Lord of the Rings Mod]([1.5.2] The Lord of the Rings Mod Public Beta 5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ReiMinimap{v3.3_05 [1.5.2]} [mod_ReiMinimap]([1.5.2]ReiMinimap_v3.3_05.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FriendsOverlay{3.1.1} [FriendsOverlay]([MC1.5.2]FriendsOverlay_3.1.1-1305031916-4-a8a000b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_FriendsOverlay{Not available} [mod_FriendsOverlay]([MC1.5.2]FriendsOverlay_3.1.1-1305031916-4-a8a000b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{1.115.308-lf} [IndustrialCraft 2](industrialcraft-2_1.115.308-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AdvancedMachines{4.9} [IC2 Advanced Machines Addon](AdvancedMachines_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{jenkins-Buildcraft-157.157} [BuildCraft](BuildCraft-1.5.2-jenkins-Buildcraft-157.157.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{jenkins-Buildcraft-157.157} [BC Transport](BuildCraft-1.5.2-jenkins-Buildcraft-157.157.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{jenkins-Buildcraft-157.157} [BC Silicon](BuildCraft-1.5.2-jenkins-Buildcraft-157.157.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv.10.l} [Applied Energistics](appeng-rv10-l.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.2.0} [BiblioCraft](BiblioCraft[v1.2.0].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{jenkins-Buildcraft-157.157} [BC Builders](BuildCraft-1.5.2-jenkins-Buildcraft-157.157.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{jenkins-Buildcraft-157.157} [BC Energy](BuildCraft-1.5.2-jenkins-Buildcraft-157.157.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{jenkins-Buildcraft-157.157} [BC Factory](BuildCraft-1.5.2-jenkins-Buildcraft-157.157.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChargePads{2.6.1} [Charge Pads](chargepads-1.5.1-universal-2.6.1.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Highlands{1.2.5} [Highlands](Highlands1.2.5-MC1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_SmartMoving{13.9} [Smart Moving](Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_SmartRender{1.1} [Smart Render](Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LWJGL: 2.4.2
    OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2270 (127120 bytes; 0 MB) allocated, 275 (15400 bytes; 0 MB) used

java.lang.NoSuchFieldError: k
    at myrathi.ic2.chargepads.j.<init>(SourceFile:25)
    at myrathi.ic2.chargepads.proxy.ClientProxy.getClientGuiElement(SourceFile:29)
    at cpw.mods.fml.common.network.NetworkRegistry.openLocalGui(NetworkRegistry.java:328)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:351)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2396)
    at cpw.mods.fml.common.network.OpenGuiPacket.execute(OpenGuiPacket.java:67)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleFMLPacket(FMLNetworkHandler.java:114)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:79)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1571)
    at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:59)
    at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
    at net.minecraft.client.multiplayer.NetClientHandler.func_72551_d(NetClientHandler.java:266)
    at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:94)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1861)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:834)
    at net.minecraft.client.Minecraft.run(Minecraft.java:759)
    at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 5ca7ca87 ----------

**Comment by Myrathi** [comment]
Tried to reproduce this locally (now that I have my machine up and running again) and have been unable to do so.

The error, however, would suggest that the client-side JAR doesn't match the server-side one. Please ensure that you have the same JAR on both.

**Comment by Sp0nge** [comment]
This happends on SSP, not SMP related. The items i tried to rightclick were spawned in using creative if that matters, not buildt manually (for testing). What i havent tried yet is removing the other mods that i have installed to see if there is a conflict of sorts (tbh i should have looked for GUI conflicts, but i guess if that was the case you would  have seen that from the errorlog?)

**Comment by Myrathi** [comment]
Strange that it's SSP. What item did you right-click the pad with? It sounds like an issue with that item as opposed to the pad.  The "NoSuchFieldError" is baffling - albeit telling - as there is, indeed, no such field on that class. No idea what's trying to access that unless something else you have installed is trying to reflect into ChargePads and change something (which doesn't exist)... but it's happening on a world-tick, so I have no idea. >_<

Can you reproduce this or was it a one-off?

**Comment by Myrathi** [comment]
Reproduced, re-opened and will look into this. Thanks for the report!

**Comment by Myrathi** [comment]
Fixed in the 1.5.2 release build.
