### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by regis9000pro** [Myrathi/ChargePadsEx#6]
Hi

It crash since i've updated ic²

java.lang.NullPointerException
    at ic2.api.item.ElectricItem.charge(ElectricItem.java:41)
    at myrathi.ic2.chargepads.s.B_(SourceFile:77)
    at myrathi.ic2.chargepads.w.C_(SourceFile:28)
    at myrathi.ic2.chargepads.d.a(SourceFile:116)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:213)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:448)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:733)
    at java.lang.Thread.run(Unknown Source)

**Comment by Myrathi** [comment]
Which versions are you using? (Chargepads, IC2 and forge) That trace, alone, is not useful.

**Comment by regis9000pro** [comment]
Ic² 317, forge 734 and charge pads 86

**Comment by Myrathi** [comment]
Hm. The API has changed since the IC2 revision that ChPv86 was built for.

Try [ChP dev build 89](https://dl.dropboxusercontent.com/u/39079855/minecraft_dev/ChargePads/1.5.2/chargepads-1.5.2-universal-2.7.1.89.jar)... though you may well have to update your IC2 build to 325.

**Comment by regis9000pro** [comment]
It work fine thanks

**Comment by Myrathi** [comment]
Good to hear! One question: did it work with 317, or did you have to update to 325 as well?

**Comment by regis9000pro** [comment]
I've
Updated ic2 and it had fixed a bug with induction furnace

**Comment by Myrathi** [comment]
Gotcha. Thanks. Closing this. :)
